### PR TITLE
Fix compare_values()

### LINKED ISSUE #56: `compare_data()` shows common values in character class columns as _missing_ and _new_
```
> x_ref <- data.frame(id = 1:5, name = random::randomStrings(5, len=5))
> x <- data.frame(id = 6:10, name = random::randomStrings(5, len=3))
> x <- rbind(x_ref, x)
> 
> print(x_ref)
  id    V1
1  1 pv6t7
2  2 JZF3z
3  3 C8I2L
4  4 nIc19
5  5 jUmsd
> print(x)
   id    V1
1   1 pv6t7
2   2 JZF3z
3   3 C8I2L
4   4 nIc19
5   5 jUmsd
6   6   O6w
7   7   1yG
8   8   CEr
9   9   b6o
10 10   NZn
> 
> compare_data(x_ref, x)

 /// Comparisons of data content // 


 // Comparison of dimensions /
  * different numbers of rows: ref has 5, new data has 10


 // Comparison of variable names /

Same variable names, in the same order

 // Comparison of variable classes /

Same variable classes

 // Comparison of values in categorical variables /

  * Missing values in `V1`:
[1] "C8I2L" "jUmsd" "JZF3z" "nIc19" "pv6t7"

  * New values in `V1`:
 [1] "1yG"   "b6o"   "C8I2L" "CEr"   "jUmsd" "JZF3z" "nIc19" "NZn"   "O6w"   "pv6t7"
```

### PR DESCRIPTION
**Pull request by zkamvar**
This will fix #56 

I've also updated the versioning scheme so that it's a bit more clear that this is still WIP.

### CODE REVIEW

**Review by ffinger — APPROVED** [review]

File: R/compare_data.R [hunk 1]
```diff
@@ -290,12 +290,12 @@ compare_values <- function(ref, x) {
...
+    ref_values_current <- ref_values[[i]]
+    x_values_current <- x_values[[i]]
 
     if (!identical(ref_values_current, x_values_current)) {
 
-      out[[i]] <- c(
+      out[[i]] <- list(
                     missing = setdiff(ref_values_current, x_values_current),
                     new = setdiff(x_values_current, ref_values_current),
                     common = intersect(x_values_current, ref_values_current))
```
Comment (ffinger) [inline R/compare_data.R:301]: Hi @zkamvar,
can you make the printing of `common` optional?
Within large datasets the output can easily become much too long.
Thanks.

Comment (zkamvar) [reply R/compare_data.R:301]: I'll create another PR for this since it's already been merged.

Comment (zkamvar) [reply R/compare_data.R:301]: This will be resolved by #60
